//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstacionamentoEstapar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Manobra
    {
        public int IdManobra { get; set; }
        public int IdModelo { get; set; }

        [Display(Name = "Placa")]
        [Required(ErrorMessage = "Informe a placa.")]
        [StringLength(100, ErrorMessage = "A marca deve ter no máximo 100 caracteres.")]
        public string DscPlaca { get; set; }
        public int IdManobrista { get; set; }
    
        public virtual Manobrista Manobrista { get; set; }
        public virtual Modelo Modelo { get; set; }
    }
}
