USE [Estapar]
GO

CREATE TABLE [dbo].[Manobrista](
	[IdManobrista] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](100) NOT NULL,
	[CPF] [varchar](14) NOT NULL,
	[DtNascimento] [date] NOT NULL,
 CONSTRAINT [PK_dbo.Manobrista] PRIMARY KEY CLUSTERED 
(
	[IdManobrista] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Marca](
	[IdMarca] [int] IDENTITY(1,1) NOT NULL,
	[DscMarca] [varchar](100) NOT NULL,
 CONSTRAINT [PK_dbo.Marca] PRIMARY KEY CLUSTERED 
(
	[IdMarca] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Modelo](
	[IdModelo] [int] IDENTITY(1,1) NOT NULL,
	[IdMarca] [int] NOT NULL,
	[DscModelo] [varchar](100) NOT NULL,
 CONSTRAINT [PK_dbo.Modelo] PRIMARY KEY CLUSTERED 
(
	[IdModelo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Modelo]
ADD CONSTRAINT FK_Modelo_Marca
FOREIGN KEY (IdMarca) REFERENCES [dbo].[Marca](IdMarca)
GO

CREATE TABLE [dbo].[Manobra](
	[IdManobra] [int] IDENTITY(1,1) NOT NULL,
	[IdModelo] [int] NOT NULL,
	[DscPlaca] [varchar](100) NOT NULL,
	[IdManobrista] [int] NOT NULL,
 CONSTRAINT [PK_dbo.Manobra] PRIMARY KEY CLUSTERED 
(
	[IdManobra] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Manobra]
ADD CONSTRAINT FK_Manobra_Modelo
FOREIGN KEY (IdModelo) REFERENCES [dbo].[Modelo](IdModelo)
GO

ALTER TABLE [dbo].[Manobra]
ADD CONSTRAINT FK_Manobra_Manobrista
FOREIGN KEY (IdManobrista) REFERENCES [dbo].[Manobrista](IdManobrista)
GO